x = matrix(1:12, ncol=3)
y = matrix(13:24, ncol=3)
print("Matrix 1")
print(x)
print("Matrix 2")
print(y)
print("After concaatenating dimensions of matrix: ")
result = dim(rbind(x,y))
print(result)
print("After concateting two given matrices: ")
print(rbind(x,y))