name =c("Asif","Shahriar","Mehedi","Mostazir")
score = c(12.5,8,4,10.3)
attempts = c(1,2,3,4)
quality = c("yes","no","yes","yes")
print("Original data frame")
print(name)
print(score)
print(attempts)
print(quality)
df= data.frame(name, score, attempts, quality)
print(df)